language: python
python:
  - "2.7"

branches:
  only:
  - master
  - beta
  - /^release-.*$/
  - ci-testing
notifications:
  flowdock: 4c5e3d825b1a21302c14ae60aaf9e36c
cache:
  directories:
    - /usr/lib/ckan/default/src/
    - $HOME/cache
  apt: true
before_install:
  - sudo apt-get update
install:
  - pip install ansible
before_script:
    - psql -c "create user ckan_default with password 'pass';" -U postgres
    - psql -c "create user drupal with password 'drupal';" -U postgres
    - psql -c "create database ckan_default;" -U postgres
    - psql -c "create database drupal;" -U postgres
    - psql -c "create extension postgis;" -U postgres
    - psql -d ckan_default -f /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql -U postgres
    - psql -d ckan_default -f /usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql -U postgres
    - psql -d "ckan_default" -c "ALTER VIEW geometry_columns OWNER TO ckan_default;" -U postgres
    - psql -d "ckan_default" -c "ALTER TABLE spatial_ref_sys OWNER TO ckan_default;" -U postgres

script:
  - "ansible-playbook -i travis/travis-ansible-inventory ansible/single-server.yml --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i travis/travis-ansible-inventory -v travis/single-server-travis.yml --connection=local --sudo --skip-tags=has-hostname,non-local,firewall,database"
