language: python
python:
  - "2.7"

branches:
  only:
  - master
  - /^release-.*$/
notifications:
  flowdock: 4c5e3d825b1a21302c14ae60aaf9e36c
cache:
  directories:
    - /usr/lib/ckan/default/src/
    - $HOME/cache
  apt: true
before_install:
  - git submodule update --init --recursive
install: ./scripts/travis-install.sh
script: ./scripts/travis-test.sh
