language: python
notifications: 
  flowdock: 4c5e3d825b1a21302c14ae60aaf9e36c
python: 
  - "2.7"
before_install:
  - git submodule update --init --recursive
install:
  - pip install flake8 --download-cache=$HOME/cache
script:
  - ./scripts/test.sh
  - flake8 --max-line-length=120 .
cache:
  apt: true
  directories:
  - /usr/lib/ckan/default/src/
  - $HOME/cache
branches:
  only:
    - master
