---
- hosts: webservers
  sudo: yes
  vars:
    sudo_group: sudo
    sudoers_temporary: /tmp/sudoers.tmp

  tasks:
  - name: Ensure keyczar is installed
    apt: pkg=python-keyczar state=latest

  - name: Ensure administrator group is present
    group: name="{{ sudo_group }}" system=yes state=present

  - name: Create sudoers temporary
    command: cp -f /etc/sudoers "{{ sudoers_temporary }}" 

  - name: Add NOPASSWD to sudoers
    lineinfile: "dest='{{ sudoers_temporary }}' state=present regexp='^%{{ sudo_group }}' line='%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'"

  - name: Check sudoers file and copy
    shell: visudo -q -c -f "{{ sudoers_temporary }}" && cp -f "{{ sudoers_temporary }}" /etc/sudoers
