---

- name: Restart Apache
  service: name=apache2 state=restarted

- name: Restart Gather
  supervisorctl: name=ckan_gather_consumer state=restarted

- name: Restart Fetch
  supervisorctl: name=ckan_fetch_consumer state=restarted

- name: Restart Celery
  supervisorctl: name=celery state=restarted

- name: Restart Celerybeat
  supervisorctl: name=celerybeat state=restarted

- name: Restart Nginx
  service: name=nginx state=restarted
