---

- name: Create paths
  file: path="{{ item }}" state=directory
  with_items: all_paths
  tags:
  - common

- name: Create files path
  file: path="{{ files_root }}" state=directory mode=0755 owner="{{ www_user }}" group="{{ www_group }}"
  tags:
  - common

- name: Copy backup script
  template: src=backup.sh.j2 dest="{{ scripts_path }}/backup.sh" mode=0750 owner=root group=root
  tags:
  - common

- name: Ensure common packages
  action: apt pkg="{{ item }}" state=latest
  with_items:
    - libpq5
    - git-core
    - unzip
    - gettext
  tags:
  - packages
  - common

- name: Package modules
  local_action: command tar cf {{ item }}.tar {{ item }} --exclude=.git --exclude-from={{ item }}/.gitignore chdir="{{ modules_path }}"
  sudo: false
  with_flattened:
    - modules
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules

- name: Copy modules
  copy: src="{{ modules_path }}/{{ item }}.tar" dest="{{ cache_path }}"
  register: modules_copy
  with_flattened:
    - modules
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules

- name: Extract modules
  shell: rm -Rf "{{ item }}" && tar xf "{{ item }}.tar" chdir="{{ cache_path }}"
  when: modules_copy|changed
  with_flattened:
    - modules
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules
