---

- name: Clear cache directory
  file: path="{{ cache_path }}" state=absent
  when: clear_all_cache
  tags:
  - common
  - clear-cache

- name: Create common paths
  file: path="{{ item }}" state=directory
  with_items: all_paths
  tags:
  - common

- name: Update packages
  apt: upgrade=dist
  tags:
  - packages
  - non-local
  - common

- name: Ensure common packages
  action: apt pkg="{{ item }}" state=latest
  with_items:
    - libpq5
    - git-core
    - unzip
    - gettext
  tags:
  - packages
  - common
