---

- name: Clear module cache
  file: path="{{ cache_path }}" state=absent
  when: clear_all_cache
  tags:
  - common
  - clear-cache

- name: Clear module cache
  file: path="{{ cache_path }}/{{ item }}" state=absent
  with_flattened:
    - modules
  when: clear_module_cache
  tags:
  - common
  - clear-cache

- name: Clear module tar cache
  file: path="{{ cache_path }}/{{ item }}.tar" state=absent
  with_flattened:
    - modules
  when: clear_module_cache
  tags:
  - common
  - clear-cache

- name: Create paths
  file: path="{{ item }}" state=directory
  with_items: all_paths
  tags:
  - common

- name: Update packages
  apt: upgrade=dist
  tags:
  - packages
  - non-local
  - common

- name: Ensure common packages
  action: apt pkg="{{ item }}" state=latest
  with_items:
    - libpq5
    - git-core
    - unzip
    - gettext
  tags:
  - packages
  - common

- name: Package modules
  local_action: command tar cf {{ item }}.tar {{ item }} --exclude=.git --exclude-from={{ item }}/.gitignore chdir="{{ modules_path }}"
  sudo: false
  with_flattened:
    - modules
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules
  - translations
  - drupal-translations

- name: Copy modules
  copy: src="{{ modules_path }}/{{ item }}.tar" dest="{{ cache_path }}"
  register: modules_copy
  with_flattened:
    - modules
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules
  - translations
  - drupal-translations

- name: Extract modules
  shell: rm -Rf "{{ item }}" && tar xf "{{ item }}.tar" chdir="{{ cache_path }}"
  when: modules_copy|changed
  with_flattened:
    - modules
  tags:
  - common
  - ckan
  - drupal
  - resources
  - modules
  - translations
