---

- name: Copy apt sources.list
  template: src=sources.list.j2 dest=/etc/apt/sources.list mode=0644 owner=root group=root
  tags:
  - packages
  - ansible

- name: Copy environment
  template: src=environment.j2 dest="/etc/environment" mode=0644 owner=root group=root
  tags:
  - ansible

- name: Set hostname
  template: src=hostname.j2 dest="/etc/hostname" mode=0644 owner=root group=root
  register: hostname_update
  tags:
  - ansible
  - has-hostname

- name: Update hostname
  command: service hostname start
  when: hostname_update|changed
  tags:
  - ansible
  - has-hostname

- name: Update package cache
  apt: update_cache=yes
  tags:
  - packages
  - ansible

- name: Ensure keyczar is installed
  apt: pkg=python-keyczar state=latest
  tags:
  - ansible

- name: Ensure ansible requirements
  action: apt pkg="{{ item }}" state=latest
  with_items:
    - python-psycopg2
    - python-virtualenv
  tags:
  - packages
  - ansible

