---

drupal_site_name: avoindata.fi
drupal_root: "{{ www_root }}/{{ drupal_name }}"

drupal_theme_path: "{{ drupal_root }}/sites/all/themes"
features_module_path: "{{ drupal_root }}/sites/all/modules/ytp_features"

bootstrap_version: "3.0.0"

drupal_upload_path: "{{ drupal_root }}/sites/default/files"

all_features:
  - language_feature
  - article_feature
  - service_alert_feature
  - article_view_feature
  - blocks_feature
  - frontpage_carousel_and_infobox_feature

translation_cache_path: "{{ cache_path }}/translations"
translation_languages:
  - "fi"
  - "sv"
translation_projects:
  - "ytp-theme-drupal"
  - "ytp-assets-common"

enable_email_verification: False
