---

- name: Create patch cache path
  file: path="{{ patches_cache_path }}" state=directory
  tags:
  - ckan
  - patch_spatial

- name: Fetch Spatial patches
  get_url: url="{{ item.patch }}" dest="{{ patches_cache_path }}/{{ item.file }}"
  register: fetch_spatial_patches
  with_items: spatial_patches
  tags:
  - ckan
  - patch_spatial

- name: Apply Spatial patches
  shell: patch -s -N -p1 < "{{ patches_cache_path }}/{{ item.file }}" chdir="{{ spatial_source_path }}"
  when: fetch_spatial_patches|changed
  ignore_errors: True
  with_items: spatial_patches
  tags:
  - ckan
  - patch_spatial
