---

# Database hostname is the first database under dbserver group in Ansible inventory file
database_host: "{{ hostvars[groups['dbserver'][0]]['inventory_hostname'] }}"
# Database is expected to be in the same subnet as the webservers
# TODO On Vagrant the private network is not the default interface, it is eth1
database_ip_range: "{% if vagrant is defined %}10.0.0.0/8{% else %}{{ ansible_default_ipv4.network }} {{ ansible_default_ipv4.netmask }}{% endif %}"
database_port: 5432

ckan_database_name: ckan_default
ckan_database_username: ckan_default
ckan_database_password: pass
ckan_database_host: "{{ database_host }}"

drupal_database_name: drupal
drupal_database_username: drupal
drupal_database_password: drupal

www_root: /var/www
www_user: www-data
www_group: www-data

drupal_name: ytp

server_path: /srv/ytp
cache_path: "{{ server_path }}/cache"
backup_path: "{{ server_path }}/backup"
scripts_path: "{{ server_path }}/scripts"
log_path: /var/log/ckan
static_path: "{{ www_root }}/static"

files_root: "{{ server_path }}/files"

all_paths:
  - "{{ server_path }}"
  - "{{ cache_path }}"
  - "{{ backup_path }}"
  - "{{ scripts_path }}"
  - "{{ log_path }}"
  - "{{ static_path }}"

drupal_hostname: "{{ inventory_hostname }}"

drupal_editor_rolename: editor
drupal_ckan_admin_rolename: ckan_admin

admin: {'username' : 'admin', 'password': 'admin', 'email': 'vagrant@localhost'}

harvest_user: {'username' : 'harvest', 'password': 'harvest', 'email': 'harvest@localhost'}

ytp_users:
  - username: 'test-editor'
    password: 'test-editor'
    email: 'editor@localhost'
  - username: 'test-publisher'
    password: 'test-publisher'
    email: 'publisher@localhost'

drupal_roles:
  - { 'username': "{{ admin.username }}", 'role': "{{ drupal_ckan_admin_rolename }}" }
  - { 'username': "test-editor", 'role': "{{ drupal_editor_rolename }}" }
  - { 'username': "test-editor", 'role': "{{ drupal_ckan_admin_rolename }}" }
  - { 'username': "test-publisher", 'role': "{{ drupal_editor_rolename }}" }

ckan_admins:
  - "{{ admin.username }}"
  - "{{ harvest_user.username }}"
  - "test-editor"

secondary_hostname: 127.0.0.1
secondary_hostname_language: en

ckan_ini: /etc/ckan/default/production.ini
virtual_environment: /usr/lib/ckan/default

harvest_sources: false

ckan_version: "2.2"

email_domain: "localhost"
email_domain_access: "localhost"
email_from: "no-reply@{{ email_domain }}"
error_email_from: "error@{{ email_domain }}"

admin_email: vagrant@localhost
error_email: "{{ admin_email }}"

google_analytics: false
# enable: google_analytics: { 'id': "", 'account': "", 'username': "", 'password': "", 'type': "" }
