---

ckan_database_name: ckan_default
ckan_database_username: ckan_default
ckan_database_password: pass

drupal_database_name: drupal
drupal_database_username: drupal
drupal_database_password: drupal  

www_root: /var/www
www_user: www-data
www_group: www-data

drupal_name: ytp

server_path: /srv/ytp
cache_path: "{{ server_path }}/cache"
backup_path: "{{ server_path }}/backup"
ansible_flags: "{{ server_path }}/ansible"
scripts_path: "{{ server_path }}/scripts"
log_path: /var/log/ckan

all_paths:
  - "{{ server_path }}"
  - "{{ cache_path }}"
  - "{{ backup_path }}"
  - "{{ ansible_flags }}"
  - "{{ scripts_path }}"
  - "{{ log_path }}"

# Ubuntu 12.04
ubuntu_codename: precise

database_ip_range: 127.0.0.1/32
database_host: localhost
database_port: 5432

drupal_admin_username: admin
drupal_admin_password: admin
drupal_admin_email: drupal@none.fake

drupal_hostname: "{{ inventory_hostname }}"

drupal_editor_rolename: editor
drupal_default_editor_username: test-editor
drupal_default_editor_email: editor@none.fake
drupal_default_editor_password: test-editor-password

drupal_ckan_admin_rolename: ckan_admin

secondary_hostname: 127.0.0.1
