---

modules:
  - ytp-assets-common
  - ckanext-drupal7
  - ckanext-ytp-drupal
  - ckanext-ytp-tasks
  - ckanext-ytp-request
  - ckanext-ytp-main
  - ckanext-googleanalytics
  - ckanext-ytp-comments
  - ytp-theme-drupal
  - ytp-drupal-wysiwyg
  - ytp-drupal-user

modules_path: ../modules

clear_module_cache: false
