---

- name: Ensure www path is present
  file: path=/var/www state=directory mode=0755 owner=root group=root
  tags:
  - resources

- name: Clean resources
  file: path=/var/www/shared state=absent
  when: modules_copy|changed
  tags:
  - resources

- name: Copy resources
  shell: cp -R {{ cache_path }}/ytp-assets-common/distribution /var/www/shared
  when: modules_copy|changed
  tags:
  - resources
