---

ckan_ini: /etc/ckan/default/production.ini
ckan_version: "2.1"
ckan_package: python-ckan_{{ ckan_version }}_amd64.deb

virtual_environment: /usr/lib/ckan/default
harvester_user: root

ckan_plugins_default: stats text_preview recline_preview
ckan_plugins: ytp_groups harvest ckan_harvester drupal7 ytp_theme ytp_drupal

harvest_username: harvest
harvest_password: harvest
harvest_email: harvest@none.fake
