---

- name: Ensure keyczar is installed
  apt: pkg=python-keyczar state=latest
  tags:
  - ansible

- name: Ensure administrator group is present
  group: name="{{ sudo_group }}" system=yes state=present
  tags:
  - ansible
  - sudoers

- name: Add NOPASSWD to sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ sudo_group }}' line='%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'"
  tags:
  - ansible
  - sudoers

- name: Copy apt sources.list
  template: src=sources.list.j2 dest=/etc/apt/sources.list mode=0644 owner=root group=root
  tags:
  - packages
  - ansible

- name: Update package cache
  apt: update_cache=yes
  tags:
  - packages
  - ansible

- name: Ensure ansible requirements
  action: apt pkg="{{ item }}" state=latest
  with_items:
    - python-psycopg2
    - python-virtualenv
  tags:
  - packages
  - ansible

