---

- name: Ensure nginx is installed
  action: apt pkg="nginx" state=latest
  tags:
    - nginx
    - packages

- name: Generate basic auth file
  template: src=htpasswd.j2 dest="{{ basic_auth_path }}" mode=0640 owner=root group="{{ www_group }}"
  when: basic_auth_path != false
  tags:
    - nginx

- name: Copy Nginx configurations
  template: src={{ item.template }} dest=/etc/nginx/{{ item.dest }} mode=0644 owner=root group=root
  with_items:
    - {'template':'nginx_site_config.j2','dest':'sites-available/ytp'}
    - {'template':'nginx.conf.j2','dest':'nginx.conf'}
  tags:
    - nginx

- name: Enable Nginx site
  file: src=/etc/nginx/sites-available/ytp dest=/etc/nginx/sites-enabled/ytp state=link
  tags:
    - nginx
  notify:
  - Restart Nginx

- name: Ensure Nginx is restarted
  service: name=nginx state=restarted
  tags:
    - nginx

- name: Set server to maintenance
  file: path="/var/www/maintenance" state=touch mode=0644 owner=root group=root
  notify: Maintenance end
  tags:
    - nginx
    - maintenance
