---

- name: Create paths
  file: path="{{ item }}" state=directory
  with_items: all_paths

- name: Copy backup script
  template: src=backup.sh.j2 dest="{{ scripts_path }}/backup.sh" mode=0750 owner=root group=root

- name: Copy environment
  template: src=environment.j2 dest="/etc/environment" mode=0644 owner=root group=root
  tags:
  - system

- name: Set hostname
  template: src=hostname.j2 dest="/etc/hostname" mode=0644 owner=root group=root
  tags:
  - system
