---

# NOTE: Database server on beta does not have a firewall as it is
#       running on an isolated security group

- hosts: dbserver
  sudo: true
  vars_files:
    - "vars/common.yml"
    - ["vars/ytp-secrets/{{ secret_variables }}", "vars/none.yml"]
    - ["vars/local.yml", "vars/none.yml"]
  roles:
    - ansible
    - users
    - clean
    - common
    - database
    - s3
    - postfix
