---

- hosts: webserver
  sudo: true
  vars_files:
    - "vars/common.yml"
    - ["vars/ytp-secrets/{{ secret_variables }}", "vars/none.yml"]
    - ["vars/local.yml", "vars/none.yml"]
  roles:
    - common
    - firewall
    - users
    - clean
    - common_webserver
    - ssl
    - nfs_client
    - nginx
    - postfix
    - ckan
    - drupal
    - data
  handlers:
    - name: restart sshd
      service: name=ssh state=restarted
