---
# Handlers

- name: Restart Apache
  service: name=apache2 state=restarted

- name: Restart Postgres
  service: name=postgresql state=restarted

- name: Restart Jetty
  service: name=jetty state=restarted

- name: Restart Gather
  supervisorctl: name=ckan_gather_consumer state=restarted

- name: Restart Fetch
  supervisorctl: name=ckan_fetch_consumer state=restarted


