---

# Changes that are required already installed system

# Drush is not installable via drush anymore.
- name: Remove old drush installation
  command: pear uninstall drush/drush removes="/usr/share/php/.registry/.channel.pear.drush.org/drush.reg"
  ignore_errors: True
  tags:
  - clean

- name: Remove old Jetty installations
  apt: pkg="{{ item }}" state=absent
  with_items:
    - solr-common
    - solr-jetty
  when: solr_host != "127.0.0.1"
  tags:
  - clean
