---

ckan_package: python-ckan_{{ ckan_version }}_amd64.deb

harvester_user: "{{ www_user }}"
celery_user: "{{ www_user }}"

ckan_plugins_default: stats
# order matters, when templates call super()
ckan_plugins: multilingual_dataset harvest ckan_harvester hri_harvester dcat dcat_rdf_harvester dcat_json_harvester dcat_json_interface spatial_metadata spatial_query csw_harvester drupal7 datarequests report archiver qa ytp_comments ytp_organizations ytp_organizations_display ytp_theme ytp_drupal ytp_tasks ytp_dataset ytp_request ytp_user ytp_service

ckan_extensions:
  - ckanext-drupal7
  - ckanext-ytp-drupal
  - ckanext-ytp-tasks
  - ckanext-ytp-request
  - ckanext-ytp-main
  - ckanext-googleanalytics
  - ckanext-ytp-comments
  - ckanext-qa
  - ckanext-datarequests
  - ckanext-harvest
  - ckanext-archiver
  - ckanext-spatial
  - ckanext-report
  - ckanext-dcat

redis_harvest_database: 0
redis_celery_database: 1

supervisor_services:
  - ckan_gather_consumer
  - ckan_fetch_consumer
  - celery_celery
  - celery_bulk
  - celery_priority
  - celerybeat

# Override these on servers! 
baker_session_secret: "9PBdkxokLGWW4M4jeTI25h+4t"
app_instance_uuid: "{dc6259b8-f112-4d23-8816-aadcede1895c}"

ckan_files_path: "{{ files_root }}/ckan"
ckan_max_resource_size: 50
translation_cache_path: "{{ cache_path }}/translations"
translation_languages:
  - "fi"
  - "sv"

translation_projects:
  - "ckanext-drupal7"
  - "ckanext-ytp-request"
  - "ckanext-ytp-drupal"
  - "ytp-assets-common"
  - "ckanext-ytp-main"
  - "ckanext-ytp-comments"
  - "ckanext-qa"
  - "ckanext-datarequests"
  - "ckanext-spatial"

ckan_site_id: "default"

patches_cache_path: "{{ cache_path }}/patch"
ckan_source_path: "{{ virtual_environment }}/src/ckan"
spatial_source_path: "{{ virtual_environment }}/src/ckanext-spatial"

ckan_patches:
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/9ae868e3c8d9177ad5c10b14f4aba01677105277.patch", file: "fix_hardcoded_languages.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/d056c0987510873e5aa752c16fb62a733b0ea16d.patch", file: "fix_multilingual_search.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/75db4d7ccde19c765ac996534994998e68924bed.patch", file: "fix_collection_type_translation.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/e0ecfc2a277298da1c369242df924955f0e742a4.patch", file: "usability-fix-for-image-upload.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/e31fdad406700e2a28703eea32100417181088bb.patch", file: "fix-template-error-in-resources.patch"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/92086374f25ccde6854ef8f5c10b5cd39530ca09.patch", file: "add-event-callbacks-to-autocomplete.patch"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/75795a88e147ec1dbc8093024408bf1841e7b31f.patch", file: "enable-celery-queues"} # ytp specific

service_database_enabled: false
auto_author_enabled: true
