---

ckan_package: python-ckan_{{ ckan_version }}_amd64.deb

ckan_user: ckan
ckan_group: ckan

harvester_user: root
celery_user: "{{ ckan_user }}"

ckan_plugins_default: stats text_preview recline_preview
ckan_plugins: ytp_organizations harvest ckan_harvester drupal7 ytp_theme ytp_drupal ytp_tasks ytp_dataset ytp_request

ckan_extensions:
  - ckanext-drupal7
  - ckanext-ytp-organizations
  - ckanext-ytp-drupal
  - ckanext-ytp-theme
  - ckanext-ytp-tasks
  - ckanext-ytp-dataset
  - ckanext-ytp-request

redis_hostname: localhost
redis_port: 6379
redis_harvest_database: 0
redis_celery_database: 1

supervisor_services:
  - ckan_gather_consumer
  - ckan_fetch_consumer
  - celery
  - celerybeat

# Override these on servers! 
baker_session_secret: "9PBdkxokLGWW4M4jeTI25h+4t"
app_instance_uuid: "{dc6259b8-f112-4d23-8816-aadcede1895c}"

ckan_files_path: "{{ files_root }}/ckan"
translation_cache_path: "{{ cache_path }}/translations"
translation_languages:
  - "fi"
  - "sv"
translation_projects:
  - "ckanext-drupal7"
  - "ckanext-ytp-request"
  - "ckanext-ytp-organizations"
  - "ckanext-ytp-dataset"
  - "ytp-assets-common"
  - "ckanext-ytp-theme"

ckan_site_id: "default"
