---

ckan_package: python-ckan_{{ ckan_version }}_amd64.deb

harvester_user: "{{ www_user }}"
celery_user: "{{ www_user }}"

ckan_plugins_default: stats
ckan_plugins: multilingual_dataset harvest ckan_harvester spatial_metadata spatial_query csw_harvester drupal7 ytp_organizations ytp_organizations_display ytp_theme ytp_drupal ytp_tasks ytp_dataset ytp_request ytp_user ytp_service

ckan_extensions:
  - ckanext-drupal7
  - ckanext-ytp-drupal
  - ckanext-ytp-tasks
  - ckanext-ytp-request
  - ckanext-ytp-main
  - ckanext-googleanalytics

redis_harvest_database: 0
redis_celery_database: 1

supervisor_services:
  - ckan_gather_consumer
  - ckan_fetch_consumer
  - celery
  - celerybeat

# Override these on servers! 
baker_session_secret: "9PBdkxokLGWW4M4jeTI25h+4t"
app_instance_uuid: "{dc6259b8-f112-4d23-8816-aadcede1895c}"

ckan_files_path: "{{ files_root }}/ckan"
translation_cache_path: "{{ cache_path }}/translations"
translation_languages:
  - "fi"
  - "sv"

translation_projects:
  - "ckanext-drupal7"
  - "ckanext-ytp-request"
  - "ckanext-ytp-drupal"
  - "ytp-assets-common"
  - "ckanext-ytp-main"

ckan_site_id: "default"

patches_cache_path: "{{ cache_path }}/patch"
ckan_source_path: "{{ virtual_environment }}/src/ckan"
spatial_source_path: "{{ virtual_environment }}/src/ckanext-spatial"

ckan_patches:
  - { patch: "https://github.com/ckan/ckan/commit/770df34be2a487b4f3b81286987cd38e74c9ebf8.patch", file: "fix_group_view.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/6f77aea762cdbc4d66ad70af0b2f1524a3a64218.patch", file: "fix_multilingual.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/0791caace461315d2cbffbcbf551ef878f23f76c.patch", file: "fix_hardcoded_languages.patch" }
  - { patch: "https://github.com/ckan/ckan/commit/549cf8359557da481080bc5318fe57b7fca26e2b.patch", file: "upgrade_select2js.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/f772576d3c480f654c39ecaeb72feb423450f200.patch", file: "fix_invalid_date_indexing.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/7df6cfc5ed044f8a4cf56c2e727522276f6a90c6.patch", file: "fix_organization_listing.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/5e686b87289fbf9824dfa42468186b8cd7ba48a2.patch", file: "fix_multilingual_search.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/9dd308b648cbf3de3211d4accac835ebcd5f71f1.patch", file: "upgrade_minified_jquery.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/7641df3acf1370642ea193c93be2a64fd4da261b.patch", file: "fix_collection_type_translation.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/77f966c54b578beb812e486372e768110a48cc98.patch", file: "fix_autocomplete_input_delay.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/c989a39ec9bd1657b6dfc5a9147ffb31f524ae33.patch", file: "upgrade_image-upload.js"}
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/b441619d98adafbfe5a1da33cec66614566949e5.patch", file: "fix-rdf.patch"}
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/7ad11f098bb03cefdf3639b6d96e3127a6d1c833.patch", file: "fix-group_show.patch"}
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/a98cb6c3ee3f82a8dc6b0fc40db1686b3c72e50a.patch", file: "refactor-multilingual-warnings.patch" }
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/8175a352f960d83027e2476489e5034cf79e43be.patch", file: "usability-fix-for-image-upload.patch" }

service_database_enabled: true
auto_author_enabled: true
