---

- name: Add Drupal roles
  command: drush role-create "{{ item }}" chdir="{{ drupal_root }}"
  ignore_errors: True
  with_items:
  - "{{ drupal_editor_rolename }}"
  - "{{ drupal_ckan_admin_rolename }}"
  tags:
  - drupal
  - roles

- name: Add permissions to editor role
  command: drush role-add-perm "{{ drupal_editor_rolename }}" "{{ item }}" chdir="{{ drupal_root }}"
  with_items:
    - create article content
    - edit own article content
    - edit any article content
    - delete own article content
    - delete any article content
    - administer comments
    - access comments
    - post comments
    - edit own comments
    - view revisions
    - revert revisions
    - delete revisions
    - create service_alert content
    - edit own service_alert content
    - edit any service_alert content
    - delete own service_alert content
    - delete any service_alert content
    - translate interface
    - translate user-defined strings
    - translate content
    - use text format filtered_html
    - use text format full_html
    - create page content
    - edit own page content
    - edit any page content
    - delete own page content
    - delete any page content
    - administer nodes
    - access content overview
    - administer url aliases
    - create url aliases
    - access toolbar
    - customize shortcut links
    - view own unpublished content
    - administer menu
    - create carousel_item content
    - edit own carousel_item content
    - edit any carousel_item content
    - delete own carousel_item content
    - delete any carousel_item content
    - create infobox_content content
    - edit own infobox_content content
    - edit any infobox_content content
    - delete own infobox_content content
    - delete any infobox_content content
  tags:
  - drupal
  - roles

- name: Add permissions to anonymous role
  command: drush role-add-perm "1" "{{ item }}" chdir="{{ drupal_root }}"
  with_items:
    - services menu retrieve menu
  tags:
  - drupal
  - roles
